name: CI

on: [push]

jobs:
  build:    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Nativefier
      run: npm install nativefier -g
    - name: Nativefy Pocket
      run: nativefier --name "Pocket" --maximize "https://app.getpocket.com" -i pocket-icon.ico
    - name: Nativefy BBC Sounds
      run: nativefier --name "BBC Sounds" --maximize "https://www.bbc.co.uk/sounds" -i bbc-sounds.ico
    - name: Nativefy PlayerFM
      run: nativefier --name "PlayerFM" --maximize "https://player.fm" -i player-fm.ico
    - uses: actions/upload-artifact@master
      with:
        name: Pocket
        path: "Pocket-win32-x64"
    - uses: actions/upload-artifact@master
      with:
        name: PlayerFM
        path: "PlayerFM-win32-x64"