name: CI

on: [push]

jobs:
  build:    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Nativefier
      run: npm install nativefier -g
    - name: Nativefy the pocket website
      run: nativefier --name "Pocket" --maximize "https://app.getpocket.com" -i icon.ico
    - uses: actions/upload-artifact@master
      with:
        name: Pocket
        path: "Pocket-win32-x64/Pocket.exe"